### ISSUE TITLE
代码运行问题

### ISSUE THREAD

**Issue by zixuanxuanxuanxuan** [wanghq21/MICN#4]
RuntimeError: The size of tensor a (120) must match the size of tensor b (72) at non-singleton dimension 1 
我想问一下这是什么问题  ，帮忙修改一下   谢谢

**Comment by wanghq21** [comment]
我运行时没有出现这个问题，你注意一下这两个点呢
1、seq_len=label_len。
2、embedding的输入是x_mark_dec而不是x_mark_enc（对应到temporal_embedding）。

**Comment by zixuanxuanxuanxuan** [comment]
![image](https://github.com/wanghq21/MICN/assets/103249246/708f0d24-4c52-43d1-872e-3daf6d958fd2)
![image](https://github.com/wanghq21/MICN/assets/103249246/68712282-d7e7-4418-b173-0375e1fcbb84)
但是当我debugETTh1这个数据集的时候，我发现x和x_mark的维度是不同的，请您查看上面的图片，x是seasonal_init_dec，x_mark是x_mark_dec，我发现seasonal_init_dec在上面做了一个concat操作变成了120维，作者可以帮忙改一下吗，谢谢

**Comment by wanghq21** [comment]
![image](https://github.com/wanghq21/MICN/assets/32741441/02b343c3-7019-42c3-9816-9ddc5cf10a96)

seasonal_init_enc 的shape 是 [batch, seq_len, enc_in], seasonal_init_dec 的shape是 [batch, seq_len+pred_len, enc_in], x_mark_dec的shape是 [batch, label_len+pred_len, 4]。而seq_len=label_len，所以seasonal_init_dec 和x_mark_dec的shape是匹配的。请问那个120和72是在什么情况得到的呢？（什么样的seq_len, label_len 和pred_len呢）

**Comment by zixuanxuanxuanxuan** [comment]
感谢您的回复，我是按照您github库里面的默认设置运行的，在您的设置里面如下图所示
![image](https://github.com/wanghq21/MICN/assets/103249246/fde23aae-8430-4ba6-8e92-73c66f87d8d2)所以这个seq_len和label_len应该是不相同的
https://github.com/wanghq21/MICN/blob/370c69b841d72246556ca05dd23163c560c22b5a/run.py#L33

**Comment by zixuanxuanxuanxuan** [comment]
可能是我的失误，我没有用脚本跑，我看着脚本里面设置的是seq_len=label_len=96,但是我看了其他的模型，这个label_len一半都设置为seq_len的一半，请问将seq_len全部作为label_len有什么意图吗，全部作为解码器的先验吗？

**Comment by wanghq21** [comment]
其他模型seq_len 和 label_len 不一样是因为他们是encoder-decoder结构，seq_len 是encoder的输入，而label_len+pred_len是decoder的输入。我们是decoder结构，只需要label_len+pred_len，为了个其他模型统一，我们也设置一个seq_len，和label_len 长度相同就行了。类似于补全的想法。论文中有提及在输入后面直接concat 0。

**Comment by zixuanxuanxuanxuan** [comment]
感谢您的回复，已经明白了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月6日(星期二) 下午3:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wanghq21/MICN] 代码运行问题 (Issue #4)





 
其他模型seq_len 和 label_len 不一样是因为他们是encoder-decoder结构，seq_len 是encoder的输入，而label_len+pred_len是decoder的输入。我们是decoder结构，只需要label_len+pred_len，为了个其他模型统一，我们也设置一个seq_len，和label_len 长度相同就行了。类似于补全的想法。论文中有提及在输入后面直接concat 0。
